Simplify and debug setbg

diff --git a/.local/bin/setbg b/.local/bin/setbg
--- a/.local/bin/setbg
+++ b/.local/bin/setbg
@@ -1,5 +1,4 @@
 #!/bin/sh
-# TODO use a WALLPAPER variable
 # TODO write $helpmsg
 
 checkin(){ # Checks paramater and respond. $2 is the flag and $1 is value.
@@ -12,37 +11,34 @@ while true; do case "$1" in
     -f | --file | -p | --directory | -i | --input) checkVal "$2" "$1" && input="$2" && shift 2 ;;
     -c | --config) checkVal "$2" "$1" && xwconfig="$2" && shift 2 ;;
     -d | --delete-orignial) deleteorig="deleteOriginalFile" && shift ;;
-	-t | --temporary) temp="temp" && shift ;;
-	-n | --nowal) nowal="noWal" && shift ;;
-	-q | --quite) quite="quiteModeNoNotification" && shift ;;
-	-h | --help) echo "$helpmsg" && exit 0 ;;
-	--) shift && break ;; # End of all options
-	-*) echo "Invalid option: $1" && echo "$helpmsg" && exit 1 ;;
-	*)  break ;; # No more options
+    -t | --temporary) temp="temp" && shift ;;
+    -n | --nowal) nowal="noWal" && shift ;;
+    -q | --quite) quite="quiteModeNoNotification" && shift ;;
+    -h | --help) echo "$helpmsg" && exit 0 ;;
+    --) shift && break ;; # End of all options
+    -*) echo "Invalid option: $1" && echo "$helpmsg" && exit 1 ;;
+    *)  break ;; # No more options
 esac ;done
 
 # Location of link to wallpaper link.
-bgloc="${XDG_DATA_HOME:-$HOME/.local/share/}/bg"
+bgloc="${XDG_DATA_HOME:-$HOME/.local/share}/bg"
 
 if [ -n "$temp" ] ;then
     [ -n "$input" ] && bgloc="$input" || echo "Temporary flag is risen but no temporary file has been declared. Using default!"
-else
+elif [ -n "$input" ] ;then
     if [ -f "$input" ] ;then
         ln -sf "$(readlink -f "$input")" "$bgloc"
-        notifmsg="Wallpaper is set"
-    else # [ -d "$input" ]
+        [ -n "$deleteorig" ] && rm "$input"
+    elif [ -d "$input" ] ;then
         ln -sf "$(find "$(readlink -f "$input")" -iregex '.*.\(jpg\|jpeg\|png\|gif\)' -type f | shuf -n 1)" "$bgloc"
         notifmsg="Random Wallpaper chosen"
     fi
-    [ -n "$deleteorig" ] && [ -f "$input" ]&& rm "$input"
 fi
-
 [ -f "$bgloc" ] || echo "No such a file!"
-
 [ -n "$nowal" ] || wal -i "$(readlink -f "$bgloc")" -o "${XDG_CONFIG_HOME:-$HOME/.config}/wal/postrun" >/dev/null 2>&1
 
 pidof dwm >/dev/null && xdotool key super+F12
-# shellcheck disable=SC2086
-xwallpaper ${xwconfig:---zoom} "$bgloc"
 
-[ -z "$quite" ] && sleep 1 && notify-send -i "$bgloc" "$notifmsg"
+# If the sleep is removed, there won't be any notification on startup
+xwallpaper ${xwconfig:---zoom} "$bgloc" &&
+    { [ -z "$quite" ] && sleep 1 && notify-send -i "$bgloc" "${notifmsg:-Wallpaper is set}" >/dev/null 2>&1 & }
